# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5

jobs:
  build-and-test: 
    executor:
      name: node/default
    steps:
      # - run:
      #     name: eslint
      #     command: |
      #       mkdir -p /tmp/test-reports/eslint
      #       node_modules/.bin/eslint . --format junit --output-file /tmp/test-reports/eslint/results.xml
      # - store_test_results:
      #     path: /tmp/test-reports
      - run:
          npm run lintfix
      - run:
          name: Install npm
          command: npm install
      - run:  
          name: Run test
          command: npm test

workflows:
  build-and-test:
    jobs:
       - build-and-test
