# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5

jobs:
  build-and-test: 
    executor:
      name: node/default
    steps:
      - run:
          npm run lint
      - run:
          name: Install npm
          command: npm install
      - run:  
          name: Run test
          command: npm test

workflows:
  build-and-test:
    jobs:
       - build-and-test
