# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5

jobs:
  build-and-test: 
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install

workflows:
  build-and-test:
    jobs:
       - build-and-test
